from pyglet.image import load, load_animation

background_img = load('assets/images/background.png')
logo_img = load('assets/images/loading_page/logo.png')
loading_img = load_animation('assets/images/loading_page/load.gif')
drums_img = load('assets/images/menu_page/drums.png')
piano_img = load('assets/images/menu_page/piano.png')
drum_set_img = load('assets/images/drum_set/drum_set.png')
piano_board_img = load('assets/images/piano_set/piano(800 x 600).jpeg')
black_spot_img = load('assets/images/piano_set/pngfind.com-black-circle-fade-png-587994_50x50.png')
white_spot_img = load('assets/images/piano_set/white Spot.png')
tabala_img = load('assets/images/menu_page/tabala.png')
inner_tabala_1_img = load('assets/images/tabala/inner_tabala_1.png')
inner_tabala_2_img = load('assets/images/tabala/inner_tabala_2.png')
middle_tabala_1_img = load('assets/images/tabala/middle_tabala_1.png')
middle_tabala_2_img = load('assets/images/tabala/middle_tabala_2.png')
outer_tabala_1_img = load('assets/images/tabala/outer_tabala_1.png')
outer_tabala_2_img = load('assets/images/tabala/outer_tabala_2.png')
stick = load('assets/images/drum_set/stick.png')
